version: '3.8'

services:
  mysql-master-test:
    image: mysql:8.0
    container_name: mysql-master-test
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    command: >
      mysqld
      --server-id=101
      --log-bin=mysql-bin
      --binlog-format=ROW
    volumes:
      - mysql-master-data:/var/lib/mysql

  mysql-replica-test:
    image: mysql:8.0
    container_name: mysql-replica-test
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    command: >
      mysqld
      --server-id=102
    volumes:
      - mysql-replica-data:/var/lib/mysql

volumes:
  mysql-master-data:
  mysql-replica-data: